AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  LoyaltyProgramDetailsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Loyalty Program Details Api
      StageName: Staging

  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./CDDemoLambda
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::148484133023:role/MyLambdaRole'
      Events:
        CDDemoApi:
          Type: Api
          Properties:
            RestApiId: !Ref LoyaltyProgramDetailsApi
            Path: /hello
            Method: GET
  CDDemoLambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./CDDemoLambda2
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::148484133023:role/MyLambdaRole'